add Pharo 11 (make Pharo 10)
hpi-swa/smalltalkCI pull request #551
Opened 2022-04-05 09:45 UTC by estebanlm

2022-04-05 12:00 UTC, fniephaus requested changes
The builds are failing due to the bash-level tests not being up-to-date. If you think we don't need them, please feel free to drop them.

2022-04-05 12:08 UTC, estebanlm commented
no, no, tests are needed!
(I just forgot they were there... doing this once each N months does that... my brain is not the same as before ;) )

On Apr 5 2022, at 2:00 pm, Fabio Niephaus ***@***.***> wrote:
>
>
> @fniephaus requested changes on this pull request.
> The builds are failing due to the bash-level tests not being up-to-date. If you think we don't need them, please feel free to drop them.
> In pharo/run.sh (https://github.com/hpi-swa/smalltalkCI/pull/551#discussion_r842697483):
>
> > @@ -21,6 +21,9 @@ pharo::get_image_url() {
> "Pharo64-stable")
> echo "get.pharo.org/64/stable"
> ;;
> + "Pharo64-11")
> + echo "get.pharo.org/64/110"
> The "Pharo32-11" image seems to be missing, you've added a VM for it below.
> In pharo/run.sh (https://github.com/hpi-swa/smalltalkCI/pull/551#discussion_r842699375):
>
> > ;;
> "Pharo64-stable")
> - echo "get.pharo.org/64/vm90"
> + echo "get.pharo.org/64/vm10"
> + ;;
> + "Pharo64-11")
> Could you please add "Pharo64-11" to the build matrix: https://github.com/hpi-swa/smalltalkCI/blob/master/.github/workflows/main.yml#L31
> —
> Reply to this email directly, view it on GitHub (https://github.com/hpi-swa/smalltalkCI/pull/551#pullrequestreview-931733867), or unsubscribe (https://github.com/notifications/unsubscribe-auth/AAD5MXWRJHK4UFIMYDYKG5TVDQTOTANCNFSM5SSFJ6CA).
> You are receiving this because you authored the thread.
>

2022-04-05 13:12 UTC, estebanlm commented
now it should be ready

2022-04-05 13:38 UTC, gcotelli commented
We can add Pharo 11 to .github/workflows/main.yml , so at least we will notice if it broke with some future changes.

2022-04-05 14:09 UTC, estebanlm commented
yeah, problem is there is no p11 image yet ;)

On Apr 5 2022, at 3:38 pm, Gabriel Omar Cotelli ***@***.***> wrote:
>
>
> We can add Pharo 11 to .github/workflows/main.yml , so at least we will notice if it broke with some future changes.
> —
> Reply to this email directly, view it on GitHub (https://github.com/hpi-swa/smalltalkCI/pull/551#issuecomment-1088715536), or unsubscribe (https://github.com/notifications/unsubscribe-auth/AAD5MXR6MDCB3JFB7ARUG3DVDQ65DANCNFSM5SSFJ6CA).
> You are receiving this because you authored the thread.
>

2022-04-09 12:10 UTC, fniephaus commented
If Pharo32-11 is only supported on arm, maybe we shouldn't support it until someone explicitly asked for it and can test it?

Please let me know when there is a Pharo 11 image, so that I can restart the checks and merge this.

2022-04-13 08:41 UTC, estebanlm commented
Hi, now we have pharo11 images. 
can you restart the CI and merge if it is appropriate?

2022-04-13 13:45 UTC, fniephaus commented
The Pharo 11 build fails with:

> Instance of UnixEnvironment did not understand #getEnv:

https://github.com/hpi-swa/smalltalkCI/runs/6008160625?check_suite_focus=true#step:4:92

2022-04-13 13:46 UTC, estebanlm commented
I know :)
working on it.

On Apr 13 2022, at 3:45 pm, Fabio Niephaus ***@***.***> wrote:
>
>
> The Pharo 11 build fails with:
> > Instance of UnixEnvironment did not understand #getEnv:
> https://github.com/hpi-swa/smalltalkCI/runs/6008160625?check_suite_focus=true#step:4:92
>
> —
> Reply to this email directly, view it on GitHub (https://github.com/hpi-swa/smalltalkCI/pull/551#issuecomment-1098069982), or unsubscribe (https://github.com/notifications/unsubscribe-auth/AAD5MXXKILG25TIV5WDZNODVE3FXPANCNFSM5SSFJ6CA).
> You are receiving this because you authored the thread.
>

2022-04-13 15:59 UTC, gcotelli approved these changes
LGTM

2022-04-13 19:15 UTC, estebanlm commented
ping

2022-04-13 19:21 UTC, fniephaus commented on repository/SmalltalkCI-Pharo-Core.package/SmalltalkCIPharo11.class/properties.json
> +	"super" : "SmalltalkCIPharo9",
I think this should eventually inherit from Pharo 10, not 9, right?

2022-04-13 19:22 UTC, fniephaus approved these changes
LGTM, thanks!

2022-04-13 19:23 UTC, merged