[improvement] now register the tested repository in iceberg for P9+
hpi-swa/smalltalkCI pull request #580
Opened 2022-11-10 10:34 UTC by hogoww

Clean redo of #579 fixing #552 !
I've enabled the registering of the repository for Pharo 9+ (therefore 10 and 11 at this time).

Pierre

2022-11-10 11:33 UTC, theseion requested changes
I like the idea!

While the change looks good, I would like to have it wrapped in an error handler. SmalltalkCI might run on anything, we can't be certain that this will be a valid Pharo repository. If it's not, the tests should still be run.

I also don't like the override too much. I think it would make sense to have an `afterLoad` method that can be overridden and would do error handling automatically.

2022-11-10 18:54 UTC, hogoww commented
> I like the idea!
 :) 

> While the change looks good, I would like to have it wrapped in an error handler. SmalltalkCI might run on anything, we can't be certain that this will be a valid Pharo repository. If it's not, the tests should still be run.

I'd have to check, but I think as long as it's a valid Monticello repository, it's valid for Iceberg.
Would that be a fair assumption to have ?
Still, I think the error handler is a good idea regardless.

> I also don't like the override too much. I think it would make sense to have an `afterLoad` method that can be overridden and would do error handling automatically.

I like that too !
Will do :)

Another thing I was planning to add in a next PR would be to add the SmalltalkCI repository to Iceberg aswell, in the pharo execution script.
That'd be easier for other purposes (such as creating a PR !)

Pierre

2022-11-10 20:02 UTC, theseion commented
> Another thing I was planning to add in a next PR would be to add the SmalltalkCI repository to Iceberg aswell, in the pharo execution script.

Might be a bit harder though, since you don't know where that repo is in relation to the one you're testing. Or do you mean to add it as a new clone?

2022-11-10 20:05 UTC, hogoww commented
Actually, since you start from a Pharo script, it's fairly easy.
That is, if my quick morning investigation was done properly ;)

2022-11-10 20:15 UTC, theseion commented
Great then :)

2022-11-11 04:29 UTC, hogoww commented
Icerberg seems to commit metadata changes silently...
Anyway, should be fine now.
@theseion does that fit your requirements? 
I wouldn't be against a better error message IMO.

2022-11-11 07:08 UTC, theseion requested changes

2022-11-11 07:08 UTC, theseion commented on repository/SmalltalkCI-Pharo-Core.package/SmalltalkCIPharo9.class/instance/postLoad.st
> +		do: [ :e | self class printWarningToStdout: 'Could not register the tested repository to Iceberg for some reason.'.
```suggestion
		do: [ :e | self class printWarningToStdout: 'Could not register the tested repository with Iceberg.'.
```

2022-11-11 17:33 UTC, theseion approved these changes

2022-11-11 17:38 UTC, theseion commented
@fniephaus You can merge this PR, unless you want to wait for @gcotelli's review.

2022-11-12 15:13 UTC, fniephaus approved these changes
LGTM, thanks!

2022-11-12 15:13 UTC, merged